### ISSUE TITLE
Listening on the wrong port

### ISSUE THREAD

**Issue by da-na** [IBM-Swift/Kitura-net#10]
Hi!
I wanted to replicate the Kitura-TodoList project with my own classes. 
The only major difference is, that in the `func setupRoutes(router: Router, messages: MessagesArray) {}`
I have provided implementation for router.use, router.all, router.get, router.options, but I have not provided implementation of router.post, router.patch, router.delete... Would that make a difference?

I've modified the provided ones (from Kitura-TodoList) and now after my new project succesfully compiles, whenever I type in browser: `http://localhost:8090/messages` in the browser I see: `Cannot GET /messages.` and in the terminal I see `INFO: spiListen(_:port:) (...)/Packages/Kitura-net-0.4.0/Sources/KituraNet/HttpServerSpi.swift line 51 - Accepted connection from: 127.0.0.1on port 36054 
UnexpectedEOF`

Why would the server accept connection on port 36054 if I explicitly try to connect on 8090? Or maybe I'm doing sth wrong?

EDIT: If I try `localhost:8090` I get `unknown` displayed in the browser window. 

Any help will be appreciated!
Thanks :)

**Comment by dfirsht** [comment]
Hey @da-na, the internal numbers do not have anything to do with what port the connection comes in on. Can you paste your routes here?

**Comment by chrisozenne** [comment]
@dfirsht: I had the same confusion as @da-na. My expectation was the same and I was surprised to see the accepted connection display a different port number for each request. I imagine if I was running a server on multiple ports that it would be more helpful to see the log telling me which of those ports was coming in to, i.e: 80 vs 443. What would be the advantage of the way that it currently is now?

**Comment by vadimeisenbergibm** [comment]
@da-na @chrisozenne I have fixed the log message to prevent the confusion - the printed port is the client port, it is not the a server port on which the application accepts incoming connections.

For more about local/remote ports and sockets, see this [Stackoverflow answer](http://stackoverflow.com/questions/152457/what-is-the-difference-between-a-port-and-a-socket?answertab=votes#tab-top)

**Comment by chrisozenne** [comment]
Thank you!!

**Comment by da-na** [comment]
Thanks for fixing the log!
@dfirsht is there an easy way to print them out ? Like print(router.debugDescription) ?  

I set them up this way: 
```
func setupRoutes(router: Router, messages: MessagesArray) {
    Log.info("SETTING UP ROUTER")

    router.use("/*", middleware: BodyParser())
    router.all("/") {
        _, _, next in next()
    }
    // Get all the messages
    router.get("/") {
        request, response, next in

        Log.info("Request: \(request)")
        let json = JSON(MessagesArray.serialize(messages.getAll()))

        response.status(HttpStatusCode.OK).sendJson(json)

        next()
    }
    // Handle options
    router.options("/*") {
        request, response, next in

        response.setHeader("Access-Control-Allow-Headers", value: "accept, content-type")
        response.setHeader("Access-Control-Allow-Methods", value: "GET")

        response.status(HttpStatusCode.OK)

        Log.info("Options handling set")

        next()
    }
}
```

**Comment by da-na** [comment]
Hi!
The solution is described here: https://github.com/SwiftyJSON/SwiftyJSON/issues/421 (using the NSDate) and is not related to routing. 

Thanks for all the help!

Would be awesome though if the *.debugDescription was added :)

**Comment by dfirsht** [comment]
Great! I'm going to close this then. Yeah I think a debug mode would help, that's something I would like to do in the future.
