### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by chrisozenne** [IBM-Swift/Kitura-net#11]
When trying to compile a Kitura project, `Kitura-net` fails to compile because of a dependency on `Kitura-HttpParserHelper` which as been recently deprecated. The compiler fails repeatedly with:

```
/Packages/Kitura-HttpParserHelper-0.4.0/utils.h:22:10: error: 'http_parser.h' file not found
```

**Comment by vadimeisenbergibm** [comment]
@chrisozenne Could you please provide more details? Which project, branch, OS, Package.swift ?

The simplest way to diagnose the problem to check the latest [Kitura Sample project](https://github.com/IBM-Swift/Kitura-Sample) master or develop branch, and compare it with your project.

**Comment by chrisozenne** [comment]
@vadimeisenbergibm: I was calling `swift build` rather than `make run` and  `swift build` would fail with the file not found errors, but `make run` seemed to get by just fine. I took a look at the Makefile but it still seems strange that I would get the errors that I did.

**Comment by vadimeisenbergibm** [comment]
@chrisozenne I see, the problem is due to the fact that you probably did not pass the flags:
`-Xswiftc -I/usr/local/include -Xlinker -L/usr/local/lib` to `swift build`, as specified in [README, Developing Kitura applications](https://github.com/IBM-Swift/Kitura#developing-kitura-applications), step 8. http_parser.h is in `/usr/local/include`, the flag `-Xswiftc -I/usr/local/include` instructs swift compiler to look there for .h files.

**Comment by chrisozenne** [comment]
@vadimeisenbergibm I was calling `swift build` because I was trying to build a project from scratch, rather than try to use `Kitura-Sample`. Currently it's very hard to build from scratch because of the dependency on the `Makefile` as well as having an initialized git repo and `Kitura-CI`. 

Also, the `Makefile` from `Kitura-CI` has the following code which assumes you are building a project named `Kitura-Sample`:
```
run: build
	@echo --- Invoking KituraSample executable
	./.build/debug/KituraSample
```

I'm trying to write some documentation on how to get started with Kitura, however it's challenging to provide a step-by-step guide that doesn't rely heavily on `Kitura-Sample` as a starting point. It's much easier for me to explain the process by starting from scratch and slowly adding in pieces and explaining why each piece is being added in one-by-one. I think `Kitura-Sample` is fantastic, but it may be an overwhelming place to start for someone who is coming from an iOS background and looking to leverage their Swift skills in building a backend to an iOS app.

**Comment by chrisozenne** [comment]
@vadimeisenbergibm Thanks for the info on the build flags. I actually had to omit those build flags for the first week or so while building Kitura because Swift would complain that it didn't recognize them, I think this had to do with some conflict with the Swift toolchain and Kitura at the time. As a result I got in the habit of just using `swift build` because at least that seemed to compile at the time. Things are changing very very fast around here :+1:. Thanks for helping me sort things out!

**Comment by chrisozenne** [comment]
My from-scratch build seems to work now. Yay!

**Comment by vadimeisenbergibm** [comment]
@chrisozenne You are right regarding the Makefile in Kitura-CI, I removed run target from it on develop branch [Makefile in Kitura-CI develop branch](https://github.com/IBM-Swift/Kitura-CI/blob/develop/build/Makefile). It will be merged into master in a couple of weeks.

Please note that the Makefile is written in such a way that you can just copy it and the script(s) in [Kitura-CI/build](https://github.com/IBM-Swift/Kitura-CI/tree/master/build) into your example project and edit/add run target. You do not have to add Kitura-CI as submodule, though I think adding Kitura-CI is the best solution if you want to stay updated with the latest changes in swift build flags used by Kitura. One of the reasons to introduce Makefile was to shield Kitura users from changes in swift build flags we had to make.

**Comment by chrisozenne** [comment]
Awesome, thanks for the tips!
