### ISSUE TITLE
ClientResponse body

### ISSUE THREAD

**Issue by Noluk1991** [IBM-Swift/Kitura-net#177]
How can I get access to ClientResponse body? Sorry, I couldn't find anything in the documentation about response's body (only status code).

**Comment by shmuelk** [comment]
Use the ClientResponse.read(...) and ClientResponse.readString() functions

**Comment by Noluk1991** [comment]
@shmuelk Thank you!

**Comment by Noluk1991** [comment]
@shmuelk Hello, can I make and contribute ClientResponse.readJSON() function? (support json response as inside-the-box feature?)

**Comment by shmuelk** [comment]
@Noluk1991 What did you plan on returning from that ClientResponse.readJSON() function?

**Comment by Noluk1991** [comment]
@shmuelk I am sorry that your time spent.
I just realized that readString result provides for the necessary JSON. (without prettyPrinted-option)
