### ISSUE TITLE
Swift debugger does not show variable values when importing KituraNet in CLion

### ISSUE THREAD

**Issue by Zig1375** [IBM-Swift/Kitura-net#191]
I have a code in CLion:

```swift
import Foundation

func d() -> String {
    let a = "Hello";
    var b = a + " ";
    b = b + "World";
    var c = b + "!"

    return c
}

print(d());
```

If I set breakpoint at line `let a = "Hello";` and press F8, I see all variable values.
But if I add `import KituraNet`, then all values won't be shown.

PS: I tried on macOS Sierra

**Comment by shmuelk** [comment]
If I'm not mistaken, CLion uses LLDB under the covers to do the actual debugging.

If that is true, then the problem you are seeing is a known LLDB problem when a module has both Swift code and C code in t, which KituraNet does at this time.

**Comment by rustymagnet3000** [comment]
you need to set the language context for lldb, when you have mixed code && you may need to `expr -l Swift -- import MySDKLib`

**Comment by ianpartridge** [comment]
Thanks for the tip!
