### ISSUE TITLE
Crashes when calling CloudKit log-in.

### ISSUE THREAD

**Issue by benspratling4** [IBM-Swift/Kitura-net#192]
In order to obtain a "web auth token", Apple's CloudKit (https://developer.apple.com/library/content/documentation/DataManagement/Conceptual/CloudKitWebServicesReference/SettingUpWebServices/SettingUpWebServices.html#//apple_ref/doc/uid/TP40015240-CH24-SW1) sends a redirect, which uses HTTP status code 421.  However, KituraNet 's HTTPStatusCode has no case for 421, so it's init.(rawValue:) method returns nil.  While KituraNet should support all known status codes, this would have been fine, had a force-unwrapped optional not been used in ClientResponse's var status didSet.    Please fix the ASAP.  In conjunction with the lack of support for ECDSA, it makes logging in to iCloud impossible with the current Kitura tools.

The appropriate code for the didSet would be:

didSet {
            statusCode = HTTPStatusCode(rawValue: status) ?? .unknown
        }

Force-unwrapped optionals should never be used in code which needs to be reliable, and a web service needs to be reliable.  The only exception is functions with no inputs.  Not just no arguments, no inputs of any kind.  Completely isolated functions (computed properties) which always produce exactly the same value and have a unit test hooked up to verify that they produce that value.  This is the only safe way to force-unwrap an optional.

**Comment by shmuelk** [comment]
This was fixed by the PR #193.

Kitura-net with the tag 1.7.5 includes this fix.
