### ISSUE TITLE
HTTP request to a Unix Socket

### ISSUE THREAD

**Issue by adellibovi** [IBM-Swift/Kitura-net#212]
Hi,

I was thinking that it would be nice to be able to make HTTP request on a Unix Socket.
There are libraries which use HTTP and sockets to expose their API.

Is this something in scope for this module? If so I would like to prepare a PR with it.

Thanks

**Comment by djones6** [comment]
#296 is merged, I'll update once we have a new release tagged.

**Comment by djones6** [comment]
Support was added in Kitura-net `2.2.0` (and Server side listening support in [Kitura `2.7.0`](https://github.com/IBM-Swift/Kitura/releases/tag/2.7.0)).
