### ISSUE TITLE
EXC_BAD_INSTRUCTION on IncomingSocketHandler.swift line 197 (only Mac OS X)

### ISSUE THREAD

**Issue by zirinisp** [IBM-Swift/Kitura-net#228]
On our development server, which is running Mac OS X 10.12.6, we are getting EXC_BAD_INSTRUCTION. So far, it was not a huge problem, as we were only using OS X for development. We are currently looking at moving our production server from bluemix to OS X, so it is essential that we sort it out.

The crash happens after the server has run for a couple of hours. As the server is used for development the traffic is minimal. I am not 100% sure, but when the server crashes I believe that there is no traffic at all. So far, I have never managed to get it running for more than 1 day without getting the crash. The only way to replicate the crash is if I wait for a couple of hours. So far I have not managed to replicate it in any other way.

The crash happens on IncomingSocketHandler.swift line 197. The method that is causing the crash is handleBufferedReadData(). The method is only run when in OSX, iOS, tvOS and under GCD_ASYNC (which I am not sure what it means). That is probably the reason that we do not get it under Linux.

A screenshot from xcode has been attached for more information.

<img width="1348" alt="screen shot 2017-11-01 at 09 50 01" src="https://user-images.githubusercontent.com/2939569/32270194-c7f0f648-beec-11e7-870f-85c604da23d5.png">
<img width="1348" alt="screen shot 2017-10-31 at 17 33 11" src="https://user-images.githubusercontent.com/2939569/32270195-c81901d8-beec-11e7-8484-cb8c90902afb.png">

**Comment by djones6** [comment]
I've been able to reproduce this locally, and am investigating a fix.

**Comment by djones6** [comment]
@zirinisp I've tagged a fix for this issue in `Kitura-net 1.7.20`.  At least, it's a fix for the same symptom, and I'm fairly confident that this will turn out to be the issue you were having.  Details of what causes the problem are described in #232.

If you continue to see this crash after updating your level of Kitura-net, please let me know.

**Comment by zirinisp** [comment]
Thank you very much. I will try it out and keep you posted if the issue comes back again.

**Comment by cloutiertyler** [comment]
I'm able to semi-consistently reproduce what appears to be similar bug on `Kitura 2.0.0`. I am running multiple Kitura HTTP servers which are communicating with each other via HTTP. I cannot for the life of me seem to track down where this is coming from. From time to time I will get a double free in the Kitura parsing logic, but it's unclear if it's related. It seems to be causing bad accesses all over the place, but not all the time.

I have a test suite that will fail ~60% of the time.

Below, for example, you can see a bad access in the middle of the PromiseKit logic.

![image](https://user-images.githubusercontent.com/6432361/32978611-916c569c-cbfa-11e7-90f1-942d89f6cf72.png)

**Comment by cloutiertyler** [comment]
Also, just out of curiosity what was the reason you guys decided to go with multiple threads over nonblocking system calls (a la `fcntl(..., F_SETFL, flags | O_NONBLOCK)`)

**Comment by cloutiertyler** [comment]
I'm running my tests through ASan and I'm actually getting quite a few data races (e.g. on the HTTPServer state, the sockets isListening Bool, etc.) I must be doing something terrible.

**Comment by djones6** [comment]
@zirinisp I'm closing this issue as fixed.
@cloutiertyler another issue was raised for data races recently (#237) - we'll investigate via that issue.
