### ISSUE TITLE
Failing to send HEAD requests with Kitura-net

### ISSUE THREAD

**Issue by AntonAleksandrov** [IBM-Swift/Kitura-net#23]
Whenever HEAD method is used request remains hanging indefinitely.

**Comment by shmuelk** [comment]
What exactly happens?

    Nothing is sent at all?
    It's sent incorrectly?

**Comment by shmuelk** [comment]
@AntonAleksandrov I think I fixed this problem with the commit above. Please try it again. Do remember to do a rm -rf .build Packages, before trying your build, or you won't pick up the new code.

**Comment by AntonAleksandrov** [comment]
Thanks, it did solve the problem.
