### ISSUE TITLE
Can not access body of ClientResponse

### ISSUE THREAD

**Issue by michalkalinowski-** [IBM-Swift/Kitura-net#24]
I'm trying to build a request handler that performs a fairly common scenario:

```
router.get("/test") {
  request, response, next in
  # send .get request to another service to get a json
  # handle json received in a response
  # send back some parts of that json as a response to /test request
}
```

My first approach was to use Http.request method that takes a closure taking ClientResponse:
```
_ = Http.request("url") {
    res in
    # do something with response
  }.end()
```

However current implementation of ClientResponse is quite limited. There is no parsing as in case of ServerResponse, and I can not even access the body of the response (the raw buffer I guess).

---
Am I approaching the entire thing in a wrong way or it's just that ClientResponse needs some development? If it's the latter I'm happy to help if you provide some guidance.

**Comment by michalkalinowski-** [comment]
Replying myself:
---
I did some more code reading and I've found a solution higher up the stack in Kitura repo. One can send the request and handle response using BodyParser.parse (feels a bit hacky though)
```
router.get("/clientRequestTest") {
  request, response, next in
  
  _ = Http.request("https://httpbin.org/get") {
    res in

    // unwrap the optional res
    guard let clientResponse = res else {
      Log.error("Log some error")
      return
    }
    
    // parse response with Kitura's BodyParser
    if let body = BodyParser.parse(clientResponse, contentType: clientResponse.headers["Content-Type"]) {
      if case .Json(let json) = body {
        Log.info("received JSON!: \(json)")
        // handle json here 
        // and send something back
        response.send(json: json)
      }
    }
  }.end()
  
  response.statusCode = .OK
  next()
}
```

**Comment by shmuelk** [comment]
I agree completely that we need a better way or perhaps a higher level way to handle communicating outward to another RESTful endpoint from within a Kitura based endpoint.

We will look into this and see what we can do (unless someone else provides a reasonable API via a PR....)

**Comment by shmuelk** [comment]
Please add any comments in our question poll in https://github.com/IBM-Swift/Kitura/issues/436
