### ISSUE TITLE
Kitura-net 0.13 fails to build CHttpParser

### ISSUE THREAD

**Issue by AntonAleksandrov** [IBM-Swift/Kitura-net#25]
We're trying to use the 0.13 tag of Kitura-Net in our SDKs, however it fails with below error. Note that 0.12 works without similar issues. 

![image](https://cloud.githubusercontent.com/assets/3949873/15128394/37e66c8a-1601-11e6-80b1-c68261f68dd8.png)

**Comment by dfirsht** [comment]
Try going to your Build settings and in the KituraNet target, add `{project path}/.build` to the Header Search Paths and the Library Search Path.

**Comment by AntonAleksandrov** [comment]
@dfirsht I've also noticed that Http was renamed to HTTP in 13.x stream, is this a permanent change?

**Comment by dfirsht** [comment]
Yes, this is to comply with swift 3 API guidelines.

**Comment by AntonAleksandrov** [comment]
Ok, this seemed to fix the problem. Thanks.

**Comment by brentmorgan** [comment]
HI, I'm having this same problem now. I've been using swift package manager so far, is it possible to make the necessary changes that way or would I need to export it to an xcode project? Either way, would you be able to give specific step by step instructions on how to make the change? I would really appreciate it!

**Comment by shmuelk** [comment]
We just use swift package generate-xcodeproj to create an XCode project for all of our repositories.

If you are still having difficulties, please include the version of Kitura-net you are using.
