### ISSUE TITLE
Allow a way to deal with unsigned certificates

### ISSUE THREAD

**Issue by bjustin-ibm** [IBM-Swift/Kitura-net#27]
I am trying to use Kitura-net to do a `POST` but the request fails because the host is using an unsigned certificate. Unfortunately, while the underlying libcurl should support this scenario, Kitura-net does not expose a way to control it.

**Comment by bjustin-ibm** [comment]
In my specific case, I need to disable both `CURLOPT_SSL_VERIFYHOST` and `CURLOPT_SSL_VERIFYPEER` in order to make my scenario work.

**Comment by dfirsht** [comment]
@bjustin-ibm I pushed an enhancement that allows curl options to be passed in. This is on its own branch atm but hopefully will be merged in soon.

**Comment by dfirsht** [comment]
@bjustin-ibm Hey we talked it over internally and decided that allowing arbitrary options to be passed in could mess things up too much. Therefore we changed the option to just allow SSL verification disabling.

**Comment by bjustin-ibm** [comment]
@dfirsht I took a peek at ee863d73d68899075ddbd7c8267028c7dda7696d and verified this should definitely work for my needs. Thanks!

**Comment by dfirsht** [comment]
Great! We just need to get this validated by @shmuelk and then we can merge this in.

**Comment by dfirsht** [comment]
Shmuel validated it and I merged it in. It is in 0.13.8.
