### ISSUE TITLE
Valid port numbers not representable

### ISSUE THREAD

**Issue by Fryie** [IBM-Swift/Kitura-net#275]
The `ClientRequest.Options` enum assumes that port numbers will be represented by [a signed 16-bit integer](https://github.com/IBM-Swift/Kitura-net/blob/master/Sources/KituraNet/ClientRequest.swift#L165). However, valid port numbers are actually [unsigned 16-bit integers](https://stackoverflow.com/a/113228/1930459).

This means that port numbers 32768-65535 (which are supposed to be valid) cannot be represented. In particular, it means that all [dynamic ports](https://en.wikipedia.org/wiki/Registered_port) won't work.

**Comment by ianpartridge** [comment]
Thank you for reporting this limitation.  We are aware of this problem - unfortunately as changing the type of a public enum's associated value case is a SemVer Major change we are stuck with this until we decide to do Kitura-net 3.0.0.

We don't have any current plans to do so as the server-side ecosystem including Kitura is migrating to https://github.com/apple/swift-nio and hence Kitura-net is gradually becoming obsolete.

So unless anyone can think of a way we can fix this without breaking SemVer Major, this is probably WONTFIX :(

**Comment by Fryie** [comment]
Thanks for the response. Maybe an ugly fix/workaround could be to introduce a new enum `ClientRequest.NewOptions` (or whatever) and add an overloaded function like `HTTP.request(_ options: NewOptions)`? I don't know how feasible / acceptable that would be.

**Comment by ianpartridge** [comment]
🤢 😀

**Comment by djones6** [comment]
@ianpartridge I recently ran into this, and was considering the workaround proposed above.  I agree it would be ugly to introduce a 'new' API, however we wouldn't have to live with it indefinitely, and could fix it properly in the next Kitura-net / Kitura-NIO major.

This issue also affects Kitura-CouchDB since it is built on top of ClientRequest.

**Comment by djones6** [comment]
Kitura-net 2.1.4 has been tagged with #285 which provides this workaround:

> In order to pass a port number greater than 32,767 (Int16.max), use the following code:
> ```swift
> let portNumber: UInt16 = 65535
> let portOption: ClientRequest.Options = .port(Int16(bitPattern: portNumber))
> ```
