### ISSUE TITLE
Compiling fails in Xcode

### ISSUE THREAD

**Issue by alexaubry** [IBM-Swift/Kitura-net#28]
**Description:**

I am trying to build a Kitura-based application in Xcode. The problem is that the Kitura-net dependency fails building. The compiler constantly throws the _no such module `CCurl`_ error. The linker also outputs : _"ditto: can't get real path for source '/Users/User/Library/Developer/Xcode/DerivedData/Projectheftrmxirszwjsegjokkskppwzwl/Build/Intermediates/Project.build/Debug/KituraNet.build/Objects-normal/x86_64/KituraNet-Swift.h'"_

Building and running works perfectly with Terminal `swift build` command. 

**Steps to reproduce:**

1. Open Xcode and make sure it is set to use the `DEVELOPMENT-SNAPSHOT-2016-05-03-a `Swift snapshot
2. Create a dummy swift package in terminal using the same Swift version.
3. Add the latest Kitura package as a dependency.
4. Run `swift build` : building should complete with no issue.
5. Run the `swift build --generate-xcodeproj` and open the generated project
6. Switch to the executable scheme and hit _⌘B_.
7. Building fails.

**Configuration:**

Xcode 7.3 public release configured with the May 3rd snapshot.

**Note:**

The failure propagates to libraries that have `Kitura-net` as a dependency, making it impossible to compile the whole project (you have to use terminal) and very hard to get code completion to work.

[See Full Xcode Build Log](https://github.com/IBM-Swift/Kitura-net/files/263483/Kitura-net-Xcodebuild-log.txt)

**Comment by alexaubry** [comment]
I finally found a workaround on OS X. It turns out you have to run `brew install curl && brew link curl --force` (as curl is _keg-only_) and not just `brew install curl`. After it got fixed, Xcode raised additional errors :

- Linking failed for CHttpParser : fixed it by building the module from terminal and added set the _FRAMEWORK_SEARCH_PATHS_ and _LIBRARY_SEARCH_PATHS_ to `$(SRCROOT)/**`.

- Module _Kitura-TemplateEngine_ not found : Renamed target to _Kitura-TemplateEngine_.

It would be nice to reflect these steps in the Wiki and to change the configuration.

**Comment by shmuelk** [comment]
@alexaubry Which version of Swift was in your path in the command line? The version you select in XCode has nothing to do with what is the path in the command line.

I ask because there have been improvements in the Swift Package Manager, that fixed many of these issues.

There is no need to do a force link of curl using brew.

As @michalkalinowski- pointed out the problem with Kitura-TemplateEngine has been fixed in our later updates on our develop branch. Make sure you are using Kitura 0.13.X. Also make sure that do an rm -rf .build Packages, before trying to do the swift build and swift build -X

**Comment by dfirsht** [comment]
The wiki has been updated to reflect the changes needed for CHttpParser and like Shmuel said, Kitura-TemplateEngine 0.13.x has the fix. Closing this issue.

**Comment by dmavromatis** [comment]
@alexaubry did you ever get this figured out?  I also want to use Kitura-net in a Cocoa application and I'm getting the same error as you.  See this: https://stackoverflow.com/questions/47167257/embedding-frameworks-from-swiftpm-into-cocoa-application-xcode
