### ISSUE TITLE
ClientRequest init(options, callback) generates invalid URI

### ISSUE THREAD

**Issue by crshnburn** [IBM-Swift/Kitura-net#29]
If a ClientRequest object is created with an array of ClientRequestOptions then the resulting URI that is created is missing '://' after the schema element.

Easiest way to recreate this is to parse a URL with URLParser and then use the fields from it as ClientRequestOptions and the resulting URL won't match the original.

**Comment by michalkalinowski-** [comment]
it's because init of client request is written like that:

``` swift

    init(options: [ClientRequestOptions], callback: ClientRequestCallback) {

        self.callback = callback

        var theSchema = "http://"
        var hostName = "localhost"
        var path = "/"
        var port: Int16? = nil

        for option in options  {
            switch(option) {
                case .Method(let method):
                    self.method = method
               ...
            }
        }

        // Adding support for Basic HTTP authentication
        let user = self.userName ?? ""
        let pwd = self.password ?? ""
        var authenticationClause = ""
        if (!user.isEmpty && !pwd.isEmpty) {
          authenticationClause = "\(user):\(pwd)@"
        }

        var portClause = ""
        if  let port = port  {
            portClause = ":\(String(port))"
        }

        // IMPORTANT HERE:
        // That is how URL is built from different ClientOptions
        url = "\(theSchema)\(authenticationClause)\(hostName)\(portClause)\(path)"

```

There is a discussion on main Kitura repo about creating a wrapper class for Client Request to make it easier to use. Until it's done and merged you need to specify scheme as:

`.scheme("https://")`

**Comment by shmuelk** [comment]
@michalkalinowski- is correct. Having said that we should make sure that the scheme in the created URL is correct (i.e. we should add :// to it if it's missing)

**Comment by crshnburn** [comment]
Ok so if the scheme should contain the `://` then the values stored in a URLParser object should contain it as well.

For now I can live with the workaround of adding `://`

**Comment by dfirsht** [comment]
Fixed in PR mentioned above.
