### ISSUE TITLE
Build failure with latest trunk Swift toolchain "swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a.xctoolchain"

### ISSUE THREAD

**Issue by fezhang** [IBM-Swift/Kitura-net#37]
Kitura-Sample/Packages/Kitura-net-0.16.0/Sources/KituraNet/ClientRequest.swift:466:47: error: cannot convert value of type '(UnsafeMutablePointer<Int8>!, Int, Int, UnsafeMutablePointer<Void>!) -> Int' to expected argument type '(@convention(c) (UnsafeMutablePointer<Int8>?, Int, Int, UnsafeMutablePointer<Void>?) -> Int)!'
        curlHelperSetOptReadFunc(handle, ptr) { (buf: UnsafeMutablePointer<Int8>!, size: Int, nMemb: Int, privateData: UnsafeMutablePointer<Void>!) -> Int in
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by shmuelk** [comment]
Kitura-net 0.16.0 builds with the 05/03 drop of Swift.

We have other branches of Kitura that compile on the 05/09 (develop), 05/31 (0531_migration) drops of Swift. Our tests against the 0531_migration branch indicated that only one minor change to Kitura* was needed. Maybe this was the one.

We currently facing some issues with our CI stream that are preventing us from upgrading our develop branch to the 05/31 or 06/06 drops of Swift.

**Comment by fezhang** [comment]
Thanks!
