### ISSUE TITLE
Can no longer build since net/helper modules moved to inline functions

### ISSUE THREAD

**Issue by aufflick** [IBM-Swift/Kitura-net#4]
Now that the curl and http helper .c/.h files have been flattened into just .h files with inline functions, I wonder how we should be building this? Since there are no longer any .c files as currently referenced in the Makefile we can't make a .a file to link in, but the swift package/build mechanism doesn't currently allow for any way to specify custom compiler flags which are needed to find eg. pcre and http-parser headers at compile time and libs at link time.

**Comment by vadimeisenbergibm** [comment]
@aufflick You can try ```swift build -Xcc -fblocks -Xswiftc -I/usr/local/include -Xlinker -L/usr/local/lib```

**Comment by aufflick** [comment]
That doesn't solve the cross-package dependencies. Oddly, even when I try
manually adding eg. -I./Packages/Kitura-HttpParserHelper-0.3.1 the build
process still can't find utils.h when building Kitura-net. Perhaps it
doesn't propagate the arguments down to the dependant project builds.

I guess I'll just write a Makefile for now :)

-- 
Mark Aufflick

**Comment by dfirsht** [comment]
@aufflick Hey we've actually added back a Makefile to help build Kitura. You should now not have any trouble now building. I'm going to close this issue but if you are still having problems, feel free to open another one.
