### ISSUE TITLE
Swap HTTPParser Swift package for http-parser

### ISSUE THREAD

**Issue by dsperling** [IBM-Swift/Kitura-net#52]
We have been working a pure Swift port of the 'C' http-parser project.

https://github.com/smithmicro/HTTPParser

Swapping HTTPParser in for http-parser would get Kitura closer to pure Swift.  Please review the performance of HTTPParser in the readme to see if it would meet the requirements of Kitura.

I will work on a PR, but I wanted to alert you to this new project and gauge interest.

**Comment by ianpartridge** [comment]
Hi @dsperling this sounds interesting. What was your reason for developing it? The Node.js HTTP parser is mature and well-used.

**Comment by rfdickerson** [comment]
Yes! Super excited about this.

1) It will make it easier to work on a Kitura application with XCode

  Right now we need to add $SRCROOT/.build/debug to the Library search paths for KituraNet and Kitura

2) Right now whenever upstream http-parser gets updated, we have to copy the c and h file to our CHttpParser library.

**Comment by ianpartridge** [comment]
Good points @rfdickerson .

@dsperling if you can open a PR we can get the new code benched to see if there's a performance impact.

**Comment by dsperling** [comment]
@ianpartridge We started developing the Swift port initially as a thought experiment.   We wanted to see how Swift 3 was performing in comparison to 'C' code and selected http-parser as our test project.  The port went quickly and we were pleased with the performance.

There is still plenty to do.  The unit tests still need work and will be 2-3 times the effort of porting the library itself.  Hopefully we can recruit some of the original authors to help out.

I will get a PR in soon.

**Comment by ianpartridge** [comment]
@dsperling cool 👍 

You might be interested in this article I read a while ago - cool work: http://www.cocoawithlove.com/blog/2016/05/01/swift-name-demangling.html

**Comment by rfdickerson** [comment]
That's very exciting work, @dsperling! Once you get a PR in, I'm curious if we can do some benchmark analysis here. Maybe @djones6 could get involved with the performance testing.

**Comment by ianpartridge** [comment]
@rfdickerson he's lined up 😉

**Comment by dsperling** [comment]
I have completed the integration of HTTPParser, but I cannot submit a PR because of a Linux linker issue.  I am wondering if you guys have seen this.

Since we now have NSURL on Linux, we did not port the URL parsing of http-parser.  So with this change:
* HTTPParser/HTTPParser.swift uses HTTPParser
* HTTPParser/URLParser.swift uses NSURL

Everything compiles and runs fine on the Mac.  Linux compiles and then produces the linker error below.  I see the same problem with the 0620 toolchain as well as Preview-2.

Here is the updated codebase:
https://github.com/smithmicro/Kitura-net

Linker error running `docker-compose up`

```
...
test_1  | swift test
test_1  | Compile Swift Module 'KituraNetTestSuite' (5 sources)
test_1  | Linking .build/debug/Kitura-netTests.xctest
test_1  | /usr/bin/ld: error: hidden symbol '_TFC10Foundation5NSURLg5_baseVS_7_CFInfo' is not defined locally
test_1  | /usr/bin/ld: error: hidden symbol '_TFC10Foundation5NSURLs5_baseVS_7_CFInfo' is not defined locally
test_1  | /usr/bin/ld: error: hidden symbol '_TFC10Foundation5NSURLm5_baseVS_7_CFInfo' is not defined locally
test_1  | /usr/bin/ld: error: hidden symbol '_TFC10Foundation5NSURLg6_flagsVs6UInt32' is not defined locally
test_1  | /usr/bin/ld: error: hidden symbol '_TFC10Foundation5NSURLs6_flagsVs6UInt32' is not defined locally
test_1  | /usr/bin/ld: error: hidden symbol '_TFC10Foundation5NSURLm6_flagsVs6UInt32' is not defined locally
test_1  | /usr/bin/ld: error: hidden symbol '_TFC10Foundation5NSURLg9_encodingVs6UInt32' is not defined locally
test_1  | /usr/bin/ld: error: hidden symbol '_TFC10Foundation5NSURLs9_encodingVs6UInt32' is not defined locally
test_1  | /usr/bin/ld: error: hidden symbol '_TFC10Foundation5NSURLm9_encodingVs6UInt32' is not defined locally
test_1  | /usr/bin/ld: error: hidden symbol '_TFC10Foundation5NSURLg7_stringGSqGSpCSo8CFString__' is not defined locally
...
```

**Comment by simplepanda** [comment]
Not sure about your linking issue but you probably want to add your ParserTests class to Tests/LinuxMain.swift to get them to test out on Linux properly.

**Comment by dsperling** [comment]
@simplepanda I am running the existing tests from Kitura-net that exercise the URLParser and HTTPParser classes.  What is different is those swift files now have a different underlying implementation.  I am trying to have URLParse.swift uses NSURL which is causing a linker error.

As a next step I will create a standalone NSURL Unit test.  If the errors persist I will open a ticket at swift.org.

**Comment by dsperling** [comment]
Interesting.  The following code is a stripped down example that duplicated the bug.  I will get this reported.

```
import Foundation

public class URLParser : NSURL {

    public init(url: NSData) {
#if os(Linux)
        super.init(string: String(data: url, encoding: NSUTF8StringEncoding) ?? "", relativeToURL: nil)!
#else
        super.init(string: String(data: url as Data, encoding: String.Encoding.utf8) ?? "", relativeTo: nil)!
#endif
    }

    // NSURL required initializers
    required convenience public init(fileReferenceLiteralResourceName path: String) {
        fatalError("init(fileReferenceLiteralResourceName:) has not been implemented")
    }
    required public init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

let _ = URLParser(url: "https://swift.org".data(using: NSUTF8StringEncoding)!)

```

**Comment by ianpartridge** [comment]
This looks very like https://bugs.swift.org/browse/SR-1901

**Comment by dsperling** [comment]
@ianpartridge Thanks for finding that.  I linked the issue in JIRA.  The issue remains in the 0725 toolchain, so I will produce a workaround so we can move forward with testing HTTPParser.

**Comment by dsperling** [comment]
PR https://github.com/IBM-Swift/Kitura-net/pull/55 submitted.

**Comment by ianpartridge** [comment]
Closing this for now, as the PR is not being merged in the short term. We can reopen if/when we want to pursue this.
