### ISSUE TITLE
POST command fails with updates from PR 54

### ISSUE THREAD

**Issue by dsperling** [IBM-Swift/Kitura-net#68]
PR https://github.com/IBM-Swift/Kitura-net/pull/54 added a "Connection: close" header, which cases certain POST commands using HTTP.request() to fail.

Here is the verbose output from CURL when used with HTTP.request().
```
*   Trying 10.0.0.1...
* Connected to a.example.com (10.0.0.1) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.example.com
> POST /exampleapi HTTP/1.1
Host: a.example.com
Accept: */*
Content-Type: application/json
Connection: close
Content-Length: 39624
Expect: 100-continue

* Done waiting for 100-continue
* We are completely uploaded and fine
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=UTF-8
< Vary: X-Origin
< Vary: Referer
< Date: Thu, 11 Aug 2016 21:14:20 GMT
< Server: ESF
...
< Accept-Ranges: none
< Vary: Origin,Accept-Encoding
< Connection: close
< 
* SSLRead() return error -9806
* Closing connection 0
```

Commenting out line 290 of ClientRequest.swift allows HTTP POST requests to work.
`//headers["Connection"] = "close"`

To make the KituraNet HTTP class more general purpose, adding the "Connection: close" header should be optional.

**Comment by collinhundley** [comment]
Interesting, I'm having the exact same problem and I posted an issue at the exact same time. See #69

**Comment by collinhundley** [comment]
@dsperling  It does look like `["Connection"] = "close"` is causing the problem, but I'm also worried about the consequences of omitting it. When it's not included, the request succeeds but this is logged at the very end:

```
* Connection #0 to host a.example.com left intact
```

Honestly I'm not 100% sure what this means, but it sounds like maybe the connection is being left open? I can't say for sure, but I imagine there was a reason somebody added that header in the first place.

**Comment by dsperling** [comment]
It was added in a PR for the "keep alive implementation", but not sure what it does yet.

Curl, which is the underlying library, does leave the connection open.  However, when you call curl_easy_cleanup() (which is called in deinit()) finally closes the connection.

https://curl.haxx.se/libcurl/c/curl_easy_cleanup.html

**Comment by collinhundley** [comment]
Maybe @shmuelk can tell us more about the `close` header.

PS, you accidentally typed 45 in the title instead of 54.

**Comment by shmuelk** [comment]
Without Connection: Close, the connection is suppose to get held open by the server. When that happened, against Kitura, we failed to get output. As HTTP.request is always a single request, I saw no need not send Connection: close.

**Comment by collinhundley** [comment]
@shmuelk Hmm, I wonder why it's causing issues with SSL on certain sites. In my case the issue occurs when accessing the Google Maps API (see #69). Is it possible that it's not following a redirect properly, or something like that?

**Comment by dsperling** [comment]
@collinhundley interesting that you see the issue with Google Maps.  I see the exact POST problem with a different Google service.

@shmuelk Do you have a test case where things were failing without "Connection: Close"?  Was it a GET?  Maybe we could figure out a solution without having to close the connection after each transaction.  At a minimum we should add a property to control this by verb or a Bool.

It would be great to allow a single KituraNet HTTP instance to transact multiple times with the same host on the same socket.  A big savings in socket setup time and TLS negotiation.

**Comment by collinhundley** [comment]
I should point out that my problem is actually with a GET to the Google API, so the issue isn't isolated to POST requests.

**Comment by dsperling** [comment]
@collinhundley Interesting that GET fails as well.  I have confirmed the bug on Linux so we can eliminate Apple's App Transport Security (ATS) as a culprit.

**Comment by shmuelk** [comment]
Unfortunately all that I remember right now, is that things were failing when Kitura tried to keep the socket open and the client didn't get any output. I'm pretty sure it was one of the Kitura-net or Kitura Unit tests that was failing, i.e. timing out waiting for output.

@dsperling Says in his PR that he has removed the addition of the connection: Close header and the Kitura-net and Kitura Unit tests are still passing. I don't know what has changed, but I'm happy to merge the PR (after a minor change mentioned on the PR).

**Comment by dsperling** [comment]
@shmuelk Fixed the typo. I double checked the unit tests on Kitura-net and Kitura on Linux and Mac.  All looks good.

If the need for the "Connection: close" has disappeared, the other option to fix this is to simply remove that one line that adds the header.  That would simplify the end() function which would no longer need the optional close Boolean.  Users that want "Connection: close" behavior can always add the header themselves.

If you want to revert to the simpler end() functions, let me know and I can modify the PR.
