### ISSUE TITLE
SSLRead() return error -9806

### ISSUE THREAD

**Issue by collinhundley** [IBM-Swift/Kitura-net#69]
When sending requests to certain sites using HTTPS, I get a `nil` response. One such site is *maps.googleapis.com*.

Enabling `CURLOPT_VERBOSE` prints this after some header information: 

```sh
SSLRead() return error -9806
```

The internet tells me that this might be an issue with CURL and App Transport Security on macOS. The headers returned are from Google, which means that the server is being reached, but it appears that CURL and/or macOS doesn't trust Google's SSL certificate.

Does anybody know how to fix this issue?

**Comment by collinhundley** [comment]
Closing this issue in favor of #68, which is identical. Looks like it might not be ATS after all.

**Comment by dsperling** [comment]
@collinhundley We opened the issues at exactly the same time!  I found this issue upgrading Kitura from 0.20 to 0.25 and one of my POST commands started failing.  Hopefully commenting out the "Connection: close" works around your problem.
