### ISSUE TITLE
urlString is never set in IncomingMessage

### ISSUE THREAD

**Issue by irar2** [IBM-Swift/Kitura-net#7]

**Comment by dfirsht** [comment]
I think it would make more sense to make urlString a computed property. Something like `public var urlString:String = {return StringUtils.fromUtf8String(url) ?? ""}`

**Comment by irar2** [comment]
I don't think urlString should be a computed property - it's only set once after http-parser completes parsing the headers. But it's a good idea to make urlString and the rest of the fields in IncomingMessage read only (by adding private(set)).

**Comment by dfirsht** [comment]
Ok since the completion of IBM-Swift/Kitura#251 which address the above issue, we can close this.
