### ISSUE TITLE
Asynchronous ClientRequest

### ISSUE THREAD

**Issue by collinhundley** [IBM-Swift/Kitura-net#73]
Is there any plan to implement an asynchronous version of `ClientRequest`? Or, is the plan to defer this functionality to `NSURLRequest` once it becomes available?

It just occurred to me that `ClientRequest` is actually synchronous, which causes some concern for my application. Since completion handlers are called before the `end()` method returns, this can result in infinite recursion for applications designed for async networking.

**Comment by ianpartridge** [comment]
@shmuelk ?

**Comment by shmuelk** [comment]
The current plans are to deprecate the KituraNet.ClientRequest and KituraNet.ClientResponse classes once URLSession is completely working on Linux.

Kitura-Request is our higher level HTTP Client client, it currently uses KituraNet.ClientRequest. There is already a branch waiting to be merged that use URLSession.

**Comment by collinhundley** [comment]
`URLSession` has been working well for me on 3.0.1, with a couple small exceptions (like the `shared` session). It looks like they haven't touched it in about a month now - I'm surprised they've left one of the most important APIs unfinished for so long? I don't know what the official roadmap is but 3.0.1 looks ok so far.
