### ISSUE TITLE
Should use symbolic name for error instead of hardcoding value.

### ISSUE THREAD

**Issue by billabt** [IBM-Swift/Kitura-net#8]
In **HttpServerSpi.swift, line 60**, the BlueSocketError errorCode property is being checked for the hard coded *-9994* value for `BlueSocket.SOCKET_ERR_ACCEPT_FAILED`.  It should be using the *symbolic* name instead.  While this value hasn't changed recently, others have and it's generally a better idea to use the *symbolic* name instead of the actual value.

**Comment by billabt** [comment]
With the latest release of BlueSocket, BlueSocketError became BlueSocket.Error.  No other changes in BlueSocket should affect Kitura.

**Comment by billabt** [comment]
Oops, almost forgot, the closed PR (https://github.com/IBM-Swift/Kitura-net/pull/12) is also fixed in the latest BlueSocket.

The version of BlueSocket that contains these fixes is 0.2.0.

**Comment by billabt** [comment]
The BlueSocket.Error change was made however, the original problem of using the hard coded *-9994* value for `BlueSocket.SOCKET_ERR_ACCEPT_FAILED` is still there.  It should be using the *symbolic* name instead.

**Comment by dfirsht** [comment]
@billabt This was changed in the develop branch

**Comment by billabt** [comment]
Sorry, my bad.

**Comment by dfirsht** [comment]
Validated through automatic testing.
