### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by buckstephenh** [IBM-Swift/Kitura-net#86]
Hi, I am looking at some greenfield development and would like to make use of HTTP/2 PUSH_PROMISE.  Any idea if/when http/2 will be supported in Kitura or do I need to make a mess and try to write it?  I am seeing support in WKWebView on the IOS client side lots of server-side but would like to see it somewhere via Swift on the server side as in Kitura. https://github.com/http2/http2-spec/wiki/Implementations

**Comment by kweinmeister** [comment]
FYI, we have not evaluated this PR yet, but you may find it of interest: https://github.com/IBM-Swift/CCurl/pull/6

**Comment by shmuelk** [comment]
@buckstephenh Am I correct in that you are looking for HTTP/2 support on the **server** side of things? If so, the PR IBM-Swift/CCurl#6 is not relevant. That one is for the client side of things.

**Comment by buckstephenh** [comment]
Yes server-side.  I think http/2 will be huge in terms of responsiveness and increased scalability of servers.  Please let me know how I can help.

**Comment by simplepanda** [comment]
I'd point out that in the interim Kitura supports FastCGI so you can use something like Nginx ahead of Kitura to handle HTTP2/SSL/static content etc.

**Comment by buckstephenh** [comment]
How do you propose a server push_promise via fastcgi?  I didn’t realize fastcgi was two-way.  Is it?  What normally is the slave of inbound requests can initiate outbound calls via fastcgi to the web server?

**Comment by na-gupta** [comment]
Issue moved to [IBM-Swift/Kitura #895](https://github.com/IBM-Swift/Kitura/issues/895) via [**ZenHub**](https://www.zenhub.com/)
